name:  extensions
version: 0.2.0
author: Ali Afshar <afshar@google.com>
description:  Plugins for Dart applications.
homepage: https://github.com/aliafshar/dart-extensions

dependencies:
  unittest: any